#Beanstalk exposes port 5000 by default
server:
  port: 5000

logging:
    level:
      com.sbd.reinvent:DEBUG

#amazon:
#  dynamodb:
#    endpoint: http://dynamodb.us-east-1.amazonaws.com/
#  aws:
#    accesskey: ${SHELL}
#    secretkey: ${SHELL}
