#Beanstalk exposes port 5000 by default
server:
  port: 5000

logging:
    level:
      com.sbd.reinvent:DEBUG

amazon:
  dynamodb:
    endpoint: ${dynamo}
  aws:
    accesskey: ${accesskey}
    secretkey: ${secretkey}
