package com.bah.reinvent.model;

import java.io.Serializable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "student_attrib")
public class StudentAttrib implements Serializable {

    private String classId;
    private String studentAttribId;
    private String studentAttribDateCreated;
    private String studentAttribHeightFeet;
    private String studentAttribHeightInches;
    private String studentAttribWeightPounds;
    private String studentAttribBmi;
    private String studentAttribTricepSkinfold;
    private String studentAttribCalfSkinfold;
    private String studentAttribPercentBodyfatEntered;
    private String studentAttribPercentBodyfatCalculated;
    private String studentId;

    public StudentAttrib(){}

    @DynamoDBAttribute(attributeName = "class_id")
    public String getClassId() {
        return classId;
    }
    @DynamoDBHashKey(attributeName = "student_attrib_id")
    @DynamoDBAutoGeneratedKey
    public String getStudentAttribId() {
        return studentAttribId;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_date_created")
    public String getStudentAttribDateCreated() {
        return studentAttribDateCreated;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_height_feet")
    public String getStudentAttribHeightFeet() {
        return studentAttribHeightFeet;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_height_inches")
    public String getStudentAttribHeightInches() {
        return studentAttribHeightInches;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_weight_pounds")
    public String getStudentAttribWeightPounds() {
        return studentAttribWeightPounds;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_bmi")
    public String getStudentAttribBmi() {
        return studentAttribBmi;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_tricep_skinfold")
    public String getStudentAttribTricepSkinfold() {
        return studentAttribTricepSkinfold;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_calf_skinfold")
    public String getStudentAttribCalfSkinfold() {
        return studentAttribCalfSkinfold;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_percent_bodyfat_entered")
    public String getStudentAttribPercentBodyfatEntered() {
        return studentAttribPercentBodyfatEntered;
    }
    @DynamoDBAttribute(attributeName = "student_attrib_percent_bodyfat_calculated")
    public String getStudentAttribPercentBodyfatCalculated() {
        return studentAttribPercentBodyfatCalculated;
    }
    @DynamoDBAttribute(attributeName = "student_id")
    public String getStudentId() {
        return studentId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public void setStudentAttribId(String studentAttribId) {
        this.studentAttribId = studentAttribId;
    }

    public void setStudentAttribDateCreated(String studentAttribDateCreated) {
        this.studentAttribDateCreated = studentAttribDateCreated;
    }

    public void setStudentAttribHeightFeet(String studentAttribHeightFeet) {
        this.studentAttribHeightFeet = studentAttribHeightFeet;
    }

    public void setStudentAttribHeightInches(String studentAttribHeightInches) {
        this.studentAttribHeightInches = studentAttribHeightInches;
    }

    public void setStudentAttribWeightPounds(String studentAttribWeightPounds) {
        this.studentAttribWeightPounds = studentAttribWeightPounds;
    }

    public void setStudentAttribBmi(String studentAttribBmi) {
        this.studentAttribBmi = studentAttribBmi;
    }

    public void setStudentAttribTricepSkinfold(String studentAttribTricepSkinfold) {
        this.studentAttribTricepSkinfold = studentAttribTricepSkinfold;
    }

    public void setStudentAttribCalfSkinfold(String studentAttribCalfSkinfold) {
        this.studentAttribCalfSkinfold = studentAttribCalfSkinfold;
    }

    public void setStudentAttribPercentBodyfatEntered(String studentAttribPercentBodyfatEntered) {
        this.studentAttribPercentBodyfatEntered = studentAttribPercentBodyfatEntered;
    }

    public void setStudentAttribPercentBodyfatCalculated(String studentAttribPercentBodyfatCalculated) {
        this.studentAttribPercentBodyfatCalculated = studentAttribPercentBodyfatCalculated;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }
}
