package com.bah.reinvent.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Students")
public class Student {


    private String id;
    private String firstName;
    private String lastName;
    private String gender;
    private String birthday;
    private String heightFeet;
    private String heightInches;
    private String weight;
    private String tricepSkinFold;
    private String calfSkinFold;
    private String percentBodyFat;
    private String fat;

    public Student() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getGender() {
        return gender;
    }

    @DynamoDBAttribute
    public String getBirthday() {
        return birthday;
    }

    @DynamoDBAttribute
    public String getHeightFeet() {
        return heightFeet;
    }

    @DynamoDBAttribute
    public String getHeightInches() {
        return heightInches;
    }

    @DynamoDBAttribute
    public String getWeight() {
        return weight;
    }

    @DynamoDBAttribute
    public String getTricepSkinFold() {
        return tricepSkinFold;
    }

    @DynamoDBAttribute
    public String getCalfSkinFold() {
        return calfSkinFold;
    }

    @DynamoDBAttribute
    public String getPercentBodyFat() {
        return percentBodyFat;
    }

    @DynamoDBAttribute
    public String getFat() {
        return fat;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}