package com.bah.reinvent.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;

@DynamoDBTable(tableName = "test")
public class Test implements Serializable {


    private String testId;
    private String classId;
    private String testDate;



    public Test() {
    }

    @DynamoDBHashKey(attributeName = "test_id")
    @DynamoDBAutoGeneratedKey
    public String getTestId() {
        return testId;
    }
    @DynamoDBAttribute(attributeName = "class_id")
    public String getClassId() {
        return classId;
    }
    @DynamoDBAttribute(attributeName = "test_date")
    public String getTestDate() {
        return testDate;
    }

    public void setTestId(String testId) {
        this.testId = testId;
    }

    public void setClassId(String classId) {
        this.classId = classId;
    }

    public void setTestDate(String testDate) {
        this.testDate = testDate;
    }
}